### PR TITLE
Implement Publishers.Catch

### PR DESCRIPTION
**Pull request by MaxDesiatov**
More tests are coming soon

### CODE REVIEW

**Comment by broadwaylamb** [comment]
Damn. I'm working on this very thing right at this moment.

**Comment by MaxDesiatov** [comment]
Would you like this to be closed in favor of your PR then?

**Comment by broadwaylamb** [comment]
@MaxDesiatov probably yes, it seems like the `Catch` publisher is a bit more complex. Sorry you had to spend your time on this.

I'm also working on `TryCatch`.

**Comment by broadwaylamb** [comment]
Do you mind if I steal your test case?

**Comment by MaxDesiatov** [comment]
Absolutely not, it's super trivial, taken from Apple's doc comment for `Publishers.Catch` 😁

**Pull request closed without merging**
