### PR TITLE
Reimplement Zip to fix reference crash issue

### LINKED ISSUE #241: Zip crash
Hi!
We are experiencing a crash after upgrading from 0.11.0(internal fork) to 0.13.0 in Zip operator.
We have created a demo project as a showcase, please take a look. It only contains a test case `testExample`.
Could you take a look @broadwaylamb?

[OpenCombineTest.zip](https://github.com/OpenCombine/OpenCombine/files/10557450/OpenCombineTest.zip)

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Close #241

- Reimplement Zip to fix reference crash issue
- Add a test case for the verify

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
A crash-fix PR. Passed all the test case.

Could you help review this? cc @broadwaylamb @ArthurChi

**Comment by Kyle-Ye** [comment]
I've tried to trigger the workflow on my fork. https://github.com/Kyle-Ye/OpenCombine/pull/1

Not sure how to resolve the Windows build issue on `windows-2019, 5.7.2`. Any idea here? @compnerd 

```
Could not find a part of the path 'D:\Include\ucrt\module.modulemap'.
```

**Comment by compnerd** [comment]
@Kyle-Ye that seems odd.  Did you pass any flags?  The default flags should not be looking into the build directory for the ucrt modulemap.  Can you try with a newer toolchain by any chance?  This path has also been replaced with an overlay that is compiler driven so something newer would have a pretty different behaviour.

**Comment by Kyle-Ye** [comment]
> @Kyle-Ye that seems odd. Did you pass any flags? The default flags should not be looking into the build directory for the ucrt modulemap. Can you try with a newer toolchain by any chance? This path has also been replaced with an overlay that is compiler driven so something newer would have a pretty different behaviour.

No. I did not pass any flags manually. And other Windows CI builds (`windows2019, 5.4.2` `windows2019, 5.5.1` `windows2019, 5.6.1`) are just fine.

**Comment by Kyle-Ye** [comment]
Close in favor of #251

**Pull request closed without merging**
