### PR TITLE
Add CHANGELOG.md, bump version to 0.12.0

### PR DESCRIPTION
**Pull request by MaxDesiatov**
I find it useful to have `CHANGELOG.md`, which preserves the history if the repository migrates away from GitHub one day, or if something happens to the releases feature. Let me know if you'd like to remove the file.

### CODE REVIEW

**Review by broadwaylamb — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@broadwaylamb You mentioned I can merge urgent stuff on my own, but looks like I won't be able to do this: "Merging can be performed automatically with 1 approving review."

I also don't have CocoaPods permissions to publish a new version.

**Comment by broadwaylamb** [comment]
Can you check if you're able to merge it now?

Also, which e-mail should I use to add you as a pod owner?

**Comment by MaxDesiatov** [comment]
Please use the same email as in my GitHub profile, is that visible?

Can't merge neither this one until CI passes, nor the one with the `Zip` implementation as it requires you to approve it as someone who requested changes on it.

**Comment by broadwaylamb** [comment]
Please check now

**Comment by MaxDesiatov** [comment]
Works now, appreciated! 👍

**Pull request merged**
